name: neurobrite
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^1.0.0           # updated from 0.65.0
  intl: ^0.20.2              # updated from 0.18.1
  audioplayers: ^5.0.0       # updated from 5.2.1
  firebase_core: ^3.15.2     # updated from 2.31.0
  cloud_firestore: ^5.6.12   # added based on your outdated list, upgraded
  oktoast: ^3.3.1

  tflite_flutter: ^0.11.0    # updated from 0.9.1
  

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/models/text_emotion.tflite
    - assets/models/labels.txt
    - assets/models/vocab.json
