// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Gh7ja_RdD9sfP2IxiD5Q83MKxtin6qc',
    appId: '1:95587145544:web:67f0a90896851ba185c57d',
    messagingSenderId: '95587145544',
    projectId: 'neurobrite',
    authDomain: 'neurobrite.firebaseapp.com',
    storageBucket: 'neurobrite.firebasestorage.app',
    measurementId: 'G-5YTW5BYLNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeWj1fstsg1FjJS6hnORzC6jdDXD_AopM',
    appId: '1:95587145544:android:241d422cc6ae75f185c57d',
    messagingSenderId: '95587145544',
    projectId: 'neurobrite',
    storageBucket: 'neurobrite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBGIdMDnR5vJQSs1FsRCrm5CiZ9Rh-MGw',
    appId: '1:95587145544:ios:696623fb95f5843785c57d',
    messagingSenderId: '95587145544',
    projectId: 'neurobrite',
    storageBucket: 'neurobrite.firebasestorage.app',
    iosBundleId: 'com.example.neurobrite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBGIdMDnR5vJQSs1FsRCrm5CiZ9Rh-MGw',
    appId: '1:95587145544:ios:696623fb95f5843785c57d',
    messagingSenderId: '95587145544',
    projectId: 'neurobrite',
    storageBucket: 'neurobrite.firebasestorage.app',
    iosBundleId: 'com.example.neurobrite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-Gh7ja_RdD9sfP2IxiD5Q83MKxtin6qc',
    appId: '1:95587145544:web:ff4f0ef3c7c28f2b85c57d',
    messagingSenderId: '95587145544',
    projectId: 'neurobrite',
    authDomain: 'neurobrite.firebaseapp.com',
    storageBucket: 'neurobrite.firebasestorage.app',
    measurementId: 'G-HSNE40LD51',
  );
}
